default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: appuser
  password: P@ssw0rd
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: depoly_app_development

test:
  <<: *default
  database: depoly_app_test

production:
  <<: *default
  database: test_app_db
  username: root
  password: <%= ENV['DEPOLY_APP_DATABASE_PASSWORD'] %>
