default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: depoly_app_development

test:
  <<: *default
  database: depoly_app_test

production:
  <<: *default
  database: depoly_app_production
  username: depoly_app
  password: <%= ENV['DEPOLY_APP_DATABASE_PASSWORD'] %>
